import type { Metadata } from "next";
import "./globals.css";
import SideNav from "./ui/sidenav";
import { inter, sfPro } from "./ui/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sfPro.variable} ${inter.className} antialiased`}>
        <div className="flex h-screen flex-col md:flex-row md:overflow-hidden bg-white bg-purple bg">
          <div className="w-full flex-none md:w-[17.25rem]">
            <SideNav />
          </div>
          <div className="flex-grow p-6 md:overflow-y-auto md:p-12">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
