import type { Metadata } from "next";
import "./globals.css";
import SideNav from "@/components/ui/SideNav";
import { inter, sfPro } from "@/components/ui/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sfPro.variable} ${inter.className} antialiased`}>
        <div className="flex h-screen flex-col md:flex-row md:overflow-hidden bg-white">
          <div className="w-full flex-none md:w-fit lg:w-[17.25rem]">
            <SideNav />
          </div>
          <div className="flex-grow md:overflow-y-auto">
            
            {children}
          </div>
        </div>
        {modal}
      </body>
    </html>
  );
}
