import type { Metadata } from "next";
import "./globals.css";
import SideNav from "@/components/ui/SideNav";
import { inter, sfPro } from "@/components/ui/fonts";
import FAB from "@/components/ui/FAB";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sfPro.variable} ${inter.className} antialiased relative h-screen overflow-hidden`}
      >
        <div className="flex h-screen flex-col md:flex-row overflow-auto md:overflow-hidden bg-white">
          <div className="w-full flex-none md:w-fit lg:w-[17.25rem]">
            <SideNav />
          </div>
          <div className="flex-grow md:overflow-y-auto">{children}</div>
        </div>
        <div className="hidden md:block">{modal}</div>
        <FAB />
        <Toaster />
      </body>
    </html>
  );
}
